### ISSUE TITLE
migration from @bumple/storage

### ISSUE THREAD

**Issue by nikage** [extend-chrome/storage#10]
### Describe the bug

Hi! 
I'm thrilled that old repo was deleted without any warning. I've got a dependency on `"@bumble/storage": "^0.2.1"` 
and I get the following error once I tried to fetch old version from github sources
"@extend-chrome/storage": "https://github.com/extend-chrome/storage#v0.2.1",

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bumble%2fchrome-rxjs - Not found
npm ERR! 404 
npm ERR! 404  '@bumble/chrome-rxjs@^0.5.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@extend-chrome/storage'
npm ERR! 404 
```
the newer versions are incompatible. At least I've tried to update yet @bumple/storage some time ago and it resulted in unexpected storage key names (with some prefix in storage key name ahead AFIR).

Could you provide access for older versions with deprecation label? 
In my case I really need `"@bumble/storage": "^0.2.1"` 

### Please complete the following information:

- Library Version:
- Operating System:
- Browser:
- Node Version:

**Comment by jacksteamdev** [comment]
Hey @nikage sorry for the confusion! Glad to hear you're using `@bumble/storage`!

I've published `@bumble/storage@0.2.1` under `@extend-chrome/storage@legacy`. Hope it works out for you! :rocket: 

```sh
npm i @extend-chrome@legacy
```
