### ISSUE TITLE
Bucket.get receives an array of strings

### ISSUE THREAD

**Issue by piedrahitapablo** [extend-chrome/storage#13]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The `.get` function from the bucket also accepts an array of strings, this is not documented.

### Your Proposal for Changes
Add:

```
bucket.get(['a', 'b'])
```

as an example on the `async function bucket.get` section

Also the type for the function can be improved changing

```
get(getter: string[]): Promise<Partial<T>>;
```

to

```
get(getter:(keyof T)[]): Promise<Partial<T>>;
```

**Comment by jacksteamdev** [comment]
@piedrahitapablo Great ideas! I'd merge this PR in a second!

**Comment by jacksteamdev** [comment]
This should be covered in v1.4.4
