### ISSUE TITLE
Best solution for getting the storage size

### ISSUE THREAD

**Issue by mulfyx** [extend-chrome/storage#15]
### Is your feature request related to a problem? Please describe.

I would like a better solution for getting the storage size

### Describe the solution you'd like

```js
const size = await bucket.size();
// or
const size = await storage.size();
```

### Describe alternatives you've considered

```js
const size = Object.keys(await bucket.get()).length;
// or
const size = Object.keys(await storage.get()).length;
```

**Comment by jacksteamdev** [comment]
@mulfyx Great idea! It's true, retrieving the whole storage bucket isn't great for performance.

Do you want the number of elements in the bucket?

The bucket uses a keys array internally, so it would be easy to add something like this:

```javascript
const keys = await bucket.getKeys() // -> Array of bucket storage keys
const size = keys.length
```

Does this work for you?

I'll have some time next Tuesday do this, but if you're interested in making a PR, here's where to start: https://github.com/extend-chrome/storage/blob/405aa26894c49dc5f7e3b3bbebb5331577a8e3fb/src/bucket/index.ts#L275-L304

Most of the work is adding a test and making sure it works, but the code would be something like this:

```javascript
return {
  // ...
  async getKeys() {
    return getKeys()
  },
  // ...
}
```

**Comment by jacksteamdev** [comment]
I've put this on the `beta` channel. It'll be released next week if there are no regressions.

```sh
npm i @extend-chrome/storage@beta
```
