### ISSUE TITLE
Remove RxJS dependency

### ISSUE THREAD

**Issue by jacksteamdev** [extend-chrome/storage#8]
We shouldn't force users to use RxJS if they don't want. We will remove RxJS from this repo and create another repo called `storage-rxjs` that provides the current Observable-based API.

### TODO

1. Factor out Bucket#changeStream and Bucket#valueStream
2. Add Bucket#onChange as a [Chrome API style Event](https://github.com/extend-chrome/events-rxjs)
3. Add Bucket#getKeys as an async utility function that resolves with an array of bucket keys
4. Add Bucket#prefixKey as a utility function that takes a string and returns it as the prefixed storage key that would be used in the native Chrome Storage API
5. Add Bucket#unprefixKey as a utility function that takes a prefixed storage key and returns it stripped of the prefix
6. Create a new repo (`storage-rxjs`) that depends on this repo. Add a changeStream and a valueStream using the prefix and unprefix utility functions

This will be a breaking change since it removes Observables from the API

**Comment by jacksteamdev** [comment]
I don't think this is worth the effort. RxJS adds a lot of utility to the project. If people complain in the future, I'll reconsider.

**Comment by DmitryEfimenko** [comment]
please don't. That's pretty much the reason I actually found this lib "extra" useful!
