### ISSUE TITLE
Change dependency of @bumble/chrome-rxjs to @extend-chrome/events-rxjs

### ISSUE THREAD

**Issue by bdolly** [extend-chrome/storage#9]
Hey guys 👋 , loving the chrome API wrappers and the RxJs integration. Seems as though there may be a deprecated or migrated package hanging out in the package.json that keeps it from installing smoothly.  

### Google search terms
`@bumble/chrome-rxjs` and searched for it on npmjs.org

### Describe the bug
When installing with yarn I got a terminal error that `@bumble/chrome-rxjs` could not be found on npmjs.org. I then searched for the missing package and could not find it. To solve the bug I pulled @extend-chrome/storage down locally and changed the dependency to `@extend-chrome/events-rxjs: extend-chrome/events-rxjs` so that it pulled directly from the @extend-chrome/events-rxjs repo. After building @extend-chrome/events-rxjs I `yarn link`ed it into my project. 

### How do we reproduce?
1. create a lerna repo 
2. cd into a package/project 
3. `yarn add @extend-chrome/storage` 

### Expected behavior
Package should install without issues. 

### Actual behavior
see bug description

### Screenshots
<img width="1010" alt="Screen Shot 2020-08-29 at 4 54 15 PM" src="https://user-images.githubusercontent.com/1334131/91645959-4a024980-ea18-11ea-9629-5fc8a9fdca48.png">

### Please complete the following information:

- Library Version: 0.10.1
- Operating System: macOS Catalina 10.15.6 (19G2021)
- Browser: N/A 
- Node Version: v12.18.2
- yarn: 1.22.4
- lerna: 3.22.1

### Additional context

Installing inside a mono-repo managed with lerna, attempted to install on both the yarn workspace level as well as on the individual package level

**Comment by jacksteamdev** [comment]
@bdolly Great catch! I'll fix this tonight.

**Comment by jacksteamdev** [comment]
Just pushed a new version! Thanks!
